### PR TITLE
Tools to forward third-party log messages into apex/logrus

### PR DESCRIPTION
**Pull request by andreiko**
```go
func main() {
	log_ecslogs.InstallDefaultLogOutput(&logrus_ecslogs.Forwarder{
		Level: logrus.InfoLevel,
	})

	log.Println("you got it")
	log.Println("no more trash in stdout")
}
```
```
time="2017-04-18T17:20:39-07:00" level=info msg="you got it" 
time="2017-04-18T17:20:39-07:00" level=info msg="no more trash in stdout" 
```
```go
func main() {
	log_ecslogs.InstallDefaultLogOutput(&apex_ecslogs.Forwarder{
		Level: apexlog.InfoLevel,
	})

	apexlog.SetHandler(json.Default)

	log.Println("you got it")
	log.Println("no more trash in stdout")
}
```
```
{"fields":{},"level":"info","timestamp":"2017-04-18T17:23:53.479003856-07:00","message":"you got it"}
{"fields":{},"level":"info","timestamp":"2017-04-18T17:23:53.479222786-07:00","message":"no more trash in stdout"}
```

### CODE REVIEW

**Comment by achille-roussel** [comment]
I think I get the point of this PR but it seems a little out of place, this repo is intended to support ecs-logs for Go, I feel like those changes would better belong in the apex and logrus repos. 

Or maybe we should pull the log package compatibility layer into a different repo?

Let me know what you think.

**Comment by andreiko** [comment]
I was looking for a right place to put it and couldn't find anything better although putting it here is a stretch.

The motivation was that when I use ecs-logs-go to get correctly formatted log output for my project I would also want to deal somehow with the output of third-party libraries to avoid getting junk in the logs. Both actions fall into "set up logging" sort of things and serve a purpose to adapt one logging format to the standard one.

**Comment by andreiko** [comment]
We can totally put the compatibility layer into another repo though.

**Comment by achille-roussel** [comment]
The purpose of this repo is to provide building blocks to work with the ecs-logs format, I feel like it doesn't make sense to add support for other log formats here.

**Comment by andreiko** [comment]
Actually, I realized that the lib already contains everything needed to achieve my goal:

```go
func main() {
	handler := log_ecslogs.NewHandler(os.Stdout)
	writer := log_ecslogs.NewWriter("", log.Flags(), handler)
	log.SetOutput(writer)

	log.Println("you got it")
	log.Println("no more trash in stdout")
}
```
```
{"level":"INFO","time":"2017-04-19T11:13:48-07:00","info":{},"data":{},"message":"you got it"}
{"level":"INFO","time":"2017-04-19T11:13:48-07:00","info":{},"data":{},"message":"no more trash in stdout"}
```

**Comment by achille-roussel** [comment]
Cool! I must have mistaken what you wanted to achieve then, glad it's working the way you need.

**Pull request closed without merging**
